### ISSUE TITLE
QT openpose

### ISSUE THREAD

**Issue by cyummy** [TX-Yeager/Liver-segmentation#1]
你好。我最近也在做一个Qt工程，需要结合openpose。遇到了一些小问题，可以请教下你吗？
Ps:我是从openpose的issue区过来的，感觉还是中文交流起来方便点（捂脸）。

问题如下：
我在QT的.pro文件中包含了openpose的头文件和lib，但是具体调用相关函数时，由于包含#include <openpose/flags.hpp> 报了很多multiple definition重复定义的错，很是纳闷，想知道你是怎么解决这个问题的？谢谢啦！

**Comment by TX-Yeager** [comment]
你有调通官网的例程吗？

**Comment by cyummy** [comment]
@TX-Yeager 官网有qt的例程吗？我没找到哎，可以分享下链接吗？
我用的是ubuntu，已经把openpose  sudo make install 安装到系统环境中，并且在其他工程里可以用了，现在是想结合qt做个界面，只要在mainwindow.h中包含下面两个头问题，就会报好多重复定义的错。。。
#include <openpose/flags.hpp>
#include <openpose/headers.hpp>

.pro文件：
　
QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = myfirstTry
TEMPLATE = app
QMAKE_CXXFLAGS += -std=c++11

SOURCES += main.cpp\
        mainwindow.cpp \
    videomainwindow.cpp

HEADERS  += mainwindow.h \
    videomainwindow.h

FORMS    += mainwindow.ui \
    videomainwindow.ui

 #--add OPENCV include opencv3.3
INCLUDEPATH +=  /usr/local/include \
                /usr/local/include/opencv \
                /usr/local/include/opencv2 \
                #/home/cyummy/openpose/include/openpose \
                /usr/local/include/openpose \
                #/usr/include \
                /usr/include/gflags \


LIBS +=  /usr/local/lib/libopencv_highgui.so \
/usr/local/lib/libopencv_core.so \
/usr/local/lib/libopencv_imgproc.so \
/usr/local/lib/libopencv_imgcodecs.so \
/usr/local/lib/libopencv_video.so \
/usr/local/lib/libopencv_videoio.so \
/usr/local/lib/libopenpose.so \
#/home/cyummy/openpose/build/src/openpose/libopenpose.so \
/usr/lib/x86_64-linux-gnu/libgflags.so \
/usr/local/cuda-9.0/lib64/libcudart.so \
/usr/local/cuda-9.0/lib64/libcublas.so \
/usr/local/cuda-9.0/lib64/libcurand.so \
/usr/local/cuda-9.0/lib64/libcudnn.so

**Comment by cyummy** [comment]
问题解决啦！谢谢你～
问题原因是：
我把#include <openpose/flags.hpp>写在了mainwindow.h头文件里了，而main.cpp中又#include mainwindow.h，导致重复定义，改到mainwindow.cpp里就没有这个问题了。
还是好好再看看C++吧（捂脸
